"""Add is_active with default

Revision ID: 1b7bf6fcc731
Revises: 7f307ed323d9
Create Date: 2025-12-04 19:09:48.866059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7bf6fcc731'
down_revision = '7f307ed323d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_iot_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_iot_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
