"""Rename huella to huella_id

Revision ID: 2c7bbddbeea7
Revises: d714c4cfede0
Create Date: 2025-11-22 08:22:55.996993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c7bbddbeea7'
down_revision = 'd714c4cfede0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huella',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('huella_id', sa.Integer(), nullable=True))
        batch_op.drop_column('huella')

    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('huella_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_area_trabajo'))
        batch_op.drop_index(batch_op.f('ix_user_rfid'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('ix_user_iot_area_trabajo'), ['area_trabajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_iot_huella_id'), ['huella_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_iot_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_iot_username'), ['username'], unique=True)
        batch_op.create_foreign_key(None, 'huella', ['huella_id'], ['id'])
        batch_op.drop_column('huella')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('huella', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_iot_username'))
        batch_op.drop_index(batch_op.f('ix_user_iot_rfid'))
        batch_op.drop_index(batch_op.f('ix_user_iot_huella_id'))
        batch_op.drop_index(batch_op.f('ix_user_iot_area_trabajo'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_area_trabajo'), ['area_trabajo'], unique=False)
        batch_op.drop_column('huella_id')

    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('huella', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('huella_id')

    op.drop_table('huella')
    # ### end Alembic commands ###
