"""Initial migration

Revision ID: 7f307ed323d9
Revises: 
Create Date: 2025-12-03 00:47:42.308893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f307ed323d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huella',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('tolerancia_entrada', sa.Integer(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('tolerancia_salida', sa.Integer(), nullable=True),
    sa.Column('dias', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_iot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contrato', sa.Date(), nullable=True),
    sa.Column('area_trabajo', sa.String(length=80), nullable=True),
    sa.Column('huella_id', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['huella_id'], ['huella.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_iot_area_trabajo'), ['area_trabajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_iot_huella_id'), ['huella_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_iot_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_iot_username'), ['username'], unique=True)

    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sensor_type', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('Permitido', 'Denegado', 'Tarde', 'Presente', 'FueraHorario', name='access_status_enum'), nullable=True),
    sa.Column('rfid', sa.String(length=64), nullable=True),
    sa.Column('huella_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('action_type', sa.String(length=255), nullable=True),
    sa.Column('motivo_decision', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_iot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_log_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_access_user_date', ['user_id', 'timestamp'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('estado_entrada', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_iot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    op.create_table('failed_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=128), nullable=True),
    sa.Column('identifier_type', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_iot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user_iot.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_iot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_iot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_schedule')
    op.drop_table('schedule_audit')
    op.drop_table('failed_attempt')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_index('ix_access_user_date')
        batch_op.drop_index(batch_op.f('ix_access_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_access_log_device_id'))

    op.drop_table('access_log')
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_iot_username'))
        batch_op.drop_index(batch_op.f('ix_user_iot_rfid'))
        batch_op.drop_index(batch_op.f('ix_user_iot_huella_id'))
        batch_op.drop_index(batch_op.f('ix_user_iot_area_trabajo'))

    op.drop_table('user_iot')
    op.drop_table('schedule')
    op.drop_table('role')
    op.drop_table('huella')
    # ### end Alembic commands ###
