"""Initial migration

Revision ID: 87f58b2f962c
Revises: 
Create Date: 2025-12-02 15:43:48.463695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f58b2f962c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('access_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_user_id_fkey'), 'user_iot', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('access_log_user_id_fkey'), 'user_iot', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('action_type')

    # ### end Alembic commands ###
