"""Rename huella to huella_id

Revision ID: 963e04ac9aa8
Revises: 88fa45e0ddd2
Create Date: 2025-11-22 11:21:09.963182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e04ac9aa8'
down_revision = '88fa45e0ddd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_entrada', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('estado_entrada')

    # ### end Alembic commands ###
