"""Initial migration motivo

Revision ID: b7dda7ee221e
Revises: 87f58b2f962c
Create Date: 2025-12-02 22:10:32.720482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dda7ee221e'
down_revision = '87f58b2f962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_decision', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_column('motivo_decision')

    # ### end Alembic commands ###
