"""Rename User to User_iot and update FKs

Revision ID: d714c4cfede0
Revises: e452eeafdaa4
Create Date: 2025-11-20 18:01:20.454146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd714c4cfede0'
down_revision = 'e452eeafdaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_iot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_contrato', sa.Date(), nullable=True),
    sa.Column('area_trabajo', sa.String(length=80), nullable=True),
    sa.Column('huella', sa.LargeBinary(), nullable=True),
    sa.Column('rfid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_iot_area_trabajo'), ['area_trabajo'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_iot_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_iot_username'), ['username'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_area_trabajo'))
        batch_op.drop_index(batch_op.f('ix_user_rfid'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('access_log_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    with op.batch_alter_table('failed_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('failed_attempt_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    with op.batch_alter_table('schedule_audit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_audit_admin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('schedule_audit_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['admin_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    with op.batch_alter_table('user_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_schedule_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_iot', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_schedule_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('schedule_audit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_audit_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('schedule_audit_admin_id_fkey'), 'user', ['admin_id'], ['id'])

    with op.batch_alter_table('failed_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('failed_attempt_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('access_log_user_id_fkey'), 'user', ['user_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('genero', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_contrato', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('area_trabajo', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('huella', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('rfid', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('user_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_rfid'), ['rfid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_area_trabajo'), ['area_trabajo'], unique=False)

    with op.batch_alter_table('user_iot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_iot_username'))
        batch_op.drop_index(batch_op.f('ix_user_iot_rfid'))
        batch_op.drop_index(batch_op.f('ix_user_iot_area_trabajo'))

    op.drop_table('user_iot')
    # ### end Alembic commands ###
